spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/qipai_members
  application:
    name: qipai_members
server:
  port: 82
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/