spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/qipai_members
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
          zk-nodes: localhost:2181
          minPartitionCount: 1
          autoCreateTopics: true
          autoAddPartitions: false
        bindings:
          members:
            producer:
              configuration:
                request:
                  timeout:
                    ms: 30000
                linger:
                  ms: 5
                batch:
                  size: 16384
                  
          golds:
            producer:
              configuration:
                request:
                  timeout:
                    ms: 30000
                linger:
                  ms: 5
                batch:
                  size: 16384
                  
          scores:
            producer:
              configuration:
                request:
                  timeout:
                    ms: 30000
                linger:
                  ms: 5
                batch:
                  size: 16384
                  
          orders:
            producer:
              configuration:
                request:
                  timeout:
                    ms: 30000
                linger:
                  ms: 5
                batch:
                  size: 16384
                  
          membershiprights:
            producer:
              configuration:
                request:
                  timeout:
                    ms: 30000
                linger:
                  ms: 5
                batch:
                  size: 16384 
                  
          grade:
            producer:
              configuration:
                request:
                  timeout:
                    ms: 30000
                linger:
                  ms: 5
                batch:
                  size: 16384         

      bindings:
        members:
          destination: members
          contentType: application/json
          producer:
            partitionCount: 1
            
        membershiprights:
          destination: membershiprights
          contentType: application/json
          producer:
            partitionCount: 1
            
        grade:
          destination: grade
          contentType: application/json
          producer:
            partitionCount: 1
            
        golds:
          destination: golds
          contentType: application/json
          producer:
            partitionCount: 1
            
        scores:
          destination: scores
          contentType: application/json
          producer:
            partitionCount: 1
            
        orders:
          destination: orders
          contentType: application/json
          producer:
            partitionCount: 1
      
      
  application:
    name: qipai-members
server:
  port: 82
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/